#!/bin/bash
DATE=$(date +%d-%m-%Y)
BACKUP_DIR="/backup/data"

# Backup and Compress
tar -czvf $BACKUP_DIR/mortgage-backup-$DATE.tar.gz /data/mpt_api_db/mortgage.db

# Delete files older than 1 Year
find $BACKUP_DIR/* -mtime +365 -exec rm {} \;
